# radio config file for toise framework

#############
### booleans to apply smearing/efficiencies or not...
apply_smearing_inelasticity: False
apply_analysis_efficiency: True
apply_energy_resolution: True

#############
### detector setup scales effective area with number of stations,
detector_setup:
    nstations: 144

#############
### effective volume of radio review simulations: 144 deep (+surface) + 169 surface-only stations
# combined to one file
effective_volume:
    e: 'review_array_dict_e.json'
    mu: 'review_array_dict_mu.json'
    tau: 'review_array_dict_tau.json'
    trigger_name: "combined_array"
    # number of stations for which the veffs were generated. The veffs will be downscaled by that factor to a per-station veff.
    simulated_stations: 144

#############
### analysis efficiency is implemented as sigmoid function with
#  - minval: low energy limit for efficiency (minval values < 0 are allowed, efficiencies are limited to [0,1])
#  - maxval: high energy limit for efficiency (maxval values > 1 are allowed, efficiencies are limited to [0,1])
#  - log_turnon_gev: turning point of the sigmoid in log10(E [GeV])
#  - log_turnon_width: width of the turnon region in log10(E)

## from RNOG paper    
# analysis_efficiency:
#    minval: -0.16480194
#    maxval: 0.76853897
#    log_turnon_gev: 8.46903659
#    log_turnon_width: 1.03517252

## for gen2 review (simulations by Kaeli)
analysis_efficiency:
    minval: 0.43725862
    maxval: 0.99336176
    log_turnon_gev: 8.21735254
    log_turnon_width: 0.93403754

#############
### energy resolution for radio, best guess from Christoph for RNO-G sims
# implemented as Cauchy for larger tails compared to Gaussian
# does not take into account LPM for nue really
energy_resolution:
    loc: 0.01868963
    scale: 0.14255128

#############
### angular resolution for radio, best guess from Ilse for deep RNO-G sims
# implemented as combination of "well-reco" gaus (1) + "bad-reco" components
# fit to preliminary data for ~70 deg zenith angle, where bulk of events come from
angular_resolution:
    norm1: 0.6192978004334891
    sigma1: 3.841393561107805
    norm2: 0.2130050363262992
    sigma2: 33.95551135597404
    norm_const: 0.1676971632402118
