package:
  name: dashi
  version: 1.0

source:
  git_rev: master
  git_url: git@github.com:IceCube-SPNO/dashi.git

build:
  noarch: python
  number: 1

requirements:
  build:
    - python=2.7
    - setuptools

  run:
    - python=2.7
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base

test:
  imports:
    - dashi

about:
  home:
  license:
  license_file:
