name: toise
channels:
  - conda-forge
platforms:
  - linux-64
  - osx-64
  - osx-arm64
dependencies:
  - python >=3.8
  - numpy
  - scipy>=0.15
  - healpy
  - ipykernel
  - autograd
  - pytables
  - pandas
  - pyyaml
  - tqdm
  - toolz
  - lazy-object-proxy
  - nuflux
  - photospline
  - pip
  - pip:
    - easy-cache >=2
    - pydashi @ https://github.com/IceCube-SPNO/dashi/archive/refs/tags/v2.0.0.tar.gz#sha256=dde4d041e16d64e04e704f3f594c9158e3b0d6a5099fecf634a8b502e292d0bb
    - -e .
