name: toise
channels:
  - conda-forge
platforms:
  - linux-64
  - osx-64
  - osx-arm64
dependencies:
  - python >=3.8,<3.10
  - numpy
  - scipy>=0.15
  - healpy
  - ipykernel
  - autograd
  - pytables
  - pandas
  - pyyaml
  - tqdm
  - toolz
  - lazy-object-proxy
  - nuflux
  - photospline
  - pip
  - pip:
    - easy-cache
    - pydashi @ https://github.com/IceCube-SPNO/dashi/archive/refs/tags/v2.0.0-alpha.0.tar.gz#sha256=b2b8a179f4268d3619a72fc14f8f223f52bc9d51c3ff338863eb8b11c6bc0d5b
    - -e .
