package:
  name: newnuflux
  version: 161839

source:
  svn_rev: 161839
  svn_url: http://code.icecube.wisc.edu/svn/sandbox/cweaver/NewNuFlux
  patches:
    - 0001-link-boostpython-by-version.patch

build:
  number: 4

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - python=2.7
    - numpy
    - boost
  run:
    - python=2.7
    - {{ pin_compatible('numpy') }}
    # setuptools links to x.x.x-versioned library
    - {{ pin_compatible('boost', max_pin='x.x.x') }}

test:
  imports:
    - NewNuFlux

about:
  home:
  license:
  license_file:
