package:
  name: newnuflux
  version: 161839

source:
  svn_rev: 161839
  svn_url: http://code.icecube.wisc.edu/svn/sandbox/cweaver/NewNuFlux

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
    - boost

  run:
    - {{ pin_compatible('python', max_pin='x.x') }}
    - {{ pin_compatible('boost', max_pin='x.x') }}

about:
  home:
  license:
  license_file:
