package:
  name: newnuflux
  version: 161839

source:
  svn_rev: 161839
  svn_url: http://code.icecube.wisc.edu/svn/sandbox/cweaver/NewNuFlux

build:
  number: 3

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - python
    - numpy
    - boost
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('boost') }}

test:
  imports:
    - NewNuFlux

about:
  home:
  license:
  license_file:
