{% set name = "photospline" %}
{% set org = "cnweaver" %}
{% set version = "2.0.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "0a3368205a7971a6919483ad5b5f0fbebb74614ec1891c95bb6a4fc9d3b950d4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 2

requirements:
  build:
    - python
    - numpy >=1.7
    - suitesparse
    - cfitsio
    - cmake >=3.1
  run:
    - python
    - {{ pin_compatible('numpy', lower_bound='1.7') }}
    # see: https://github.com/conda-forge/suitesparse-feedstock/issues/22
    - {{ pin_compatible('suitesparse', max_pin='x.x.x') }}
    - cfitsio

test:
  imports:
    - photospline
