
package:
  name: photospline
  version: 2.0.1

source:
  git_rev: master
  git_url: git@github.com:cnweaver/photospline.git

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - suitesparse
    - cfitsio
    - cmake
  run:
    - python
    - numpy
    - suitesparse
    - cfitsio

