name: lint
on: [push, pull_request]
jobs:
  black:
    name: black
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: psf/black@22.3.0
        with:
          src: "toise tests"
          options: "--check --diff"
          version: "22.3.0"
